import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { gsap } from 'gsap';
import './style.css';
const host=document.querySelector('#canvas');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x061017); scene.fog=new THREE.FogExp2(0x071117,0.017);
const camera=new THREE.PerspectiveCamera(45,1,.1,200); camera.position.set(11,9,15);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; host.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.target.set(0,-3,0); controls.minDistance=5; controls.maxDistance=40;
scene.add(new THREE.HemisphereLight(0x9cbac8,0x17242b,1.2)); const dl=new THREE.DirectionalLight(0xd1eff8,2); dl.position.set(8,14,10); scene.add(dl);
const root=new THREE.Group(); scene.add(root);
const mats=[0x745b46,0x53674f,0x5c5865,0x505b61,0x6a5645].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.95,transparent:true,opacity:.48}));
const formations=new THREE.Group(); root.add(formations); for(let i=0;i<7;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(12,2,12),mats[i%mats.length]);m.position.y=-i*2-1;formations.add(m)}
const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,3,0),new THREE.Vector3(0,.5,0),new THREE.Vector3(.1,-2,0),new THREE.Vector3(.2,-4.5,0),new THREE.Vector3(.8,-7,0),new THREE.Vector3(1.8,-9.2,0),new THREE.Vector3(3,-11,0),new THREE.Vector3(4.4,-12.8,0)]);
const well=new THREE.Mesh(new THREE.TubeGeometry(curve,100,.15,12,false),new THREE.MeshStandardMaterial({color:0x69cddd,emissive:0x103b44,emissiveIntensity:1.2,transparent:true,opacity:.86,metalness:.15,roughness:.35})); root.add(well);
const casing=new THREE.Mesh(new THREE.TubeGeometry(curve,100,.23,16,false),new THREE.MeshStandardMaterial({color:0xcbd7dc,metalness:.7,roughness:.4,transparent:true,opacity:.55})); root.add(casing);
const drill=new THREE.Group(); const metal=new THREE.MeshStandardMaterial({color:0xe1e8eb,metalness:.85,roughness:.3}); for(let i=0;i<18;i++){let p=curve.getPointAt(i/18),q=curve.getPointAt(Math.min(1,i/18+.012));let x=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,.72,12),metal);x.position.copy(p);x.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.clone().sub(p).normalize());drill.add(x)} const bp=curve.getPointAt(.96),bq=curve.getPointAt(1);const bit=new THREE.Mesh(new THREE.ConeGeometry(.34,.75,16),new THREE.MeshStandardMaterial({color:0x44545c,metalness:.75,roughness:.45}));bit.position.copy(bp);bit.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),bq.clone().sub(bp).normalize());drill.add(bit);root.add(drill);
const rig=new THREE.Group(); const steel=new THREE.MeshStandardMaterial({color:0x92a2a8,metalness:.8,roughness:.45});const base=new THREE.Mesh(new THREE.BoxGeometry(4.5,.45,3.4),new THREE.MeshStandardMaterial({color:0x26383f,metalness:.5,roughness:.7}));base.position.y=3.1;rig.add(base);for(const x of[-1.5,1.5])for(const z of[-1,1]){const b=new THREE.Mesh(new THREE.BoxGeometry(.1,5.2,.1),steel);b.position.set(x,5.9,z);rig.add(b)}for(let y=4;y<=9;y++)for(const z of[-1,1]){const c=new THREE.Mesh(new THREE.BoxGeometry(3,.07,.07),steel);c.position.set(0,y,z);rig.add(c)}root.add(rig);
const marker=new THREE.Mesh(new THREE.RingGeometry(.22,.3,24),new THREE.MeshBasicMaterial({color:0x79d6e6,side:THREE.DoubleSide,transparent:true,opacity:.9})); marker.rotation.x=Math.PI/2; marker.position.copy(curve.getPointAt(.96));root.add(marker);
const grid=new THREE.GridHelper(28,28,0x29424c,0x172a33);grid.position.y=3;root.add(grid);
const states={overview:{c:[11,9,15],t:[0,-3,0],d:1,o:.48,l:'OVERVIEW',m:['4,120 m','3,680 m','142°','58°']},well:{c:[9,3.5,12],t:[1,-5,0],d:1,o:.40,l:'WELL SECTION',m:['4,120 m','3,680 m','142°','58°']},lithology:{c:[14,1.5,9],t:[0,-6,0],d:0,o:.72,l:'LITHOLOGY',m:['3,980 m','3,570 m','141°','56°']},bha:{c:[8,-1,9],t:[2.5,-10,0],d:1,o:.42,l:'DIRECTIONAL BHA',m:['4,120 m','3,680 m','142°','58°']},casing:{c:[10,5,13],t:[0,-4.5,0],d:0,o:.36,l:'CASING',m:['4,090 m','3,650 m','140°','57°']}};
const order=Object.keys(states); let current='overview';let tween;
const $=s=>document.querySelector(s); const stageLabel=$('#stageLabel'),footerStage=$('#footerStage');
function setStage(name){current=name;const s=states[name],i=order.indexOf(name);document.querySelectorAll('#stageNav button').forEach(b=>b.classList.toggle('active',b.dataset.stage===name));stageLabel.textContent=s.l;footerStage.textContent=`${String(i+1).padStart(2,'0')} / 05`;$('#md').textContent=s.m[0];$('#tvd').textContent=s.m[1];$('#azi').textContent=s.m[2];$('#inc').textContent=s.m[3];$('#bhaStatus').textContent=s.d?'Active':'Standby';$('#timeline').value=Math.round(i/(order.length-1)*100);if(tween)tween.kill();const p={x:camera.position.x,y:camera.position.y,z:camera.position.z,tx:controls.target.x,ty:controls.target.y,tz:controls.target.z,o:mats[0].opacity,co:casing.material.opacity};tween=gsap.to(p,{x:s.c[0],y:s.c[1],z:s.c[2],tx:s.t[0],ty:s.t[1],tz:s.t[2],o:s.o,co:s.d?.55:.88,duration:1,ease:'power2.inOut',onUpdate(){camera.position.set(p.x,p.y,p.z);controls.target.set(p.tx,p.ty,p.tz);mats.forEach(m=>m.opacity=p.o);casing.material.opacity=p.co}});gsap.to(drill.scale,{y:s.d?1:.0001,duration:.45,ease:'power2.inOut'})}
document.querySelectorAll('#stageNav button').forEach(b=>b.addEventListener('click',()=>setStage(b.dataset.stage)));$('#opacity').addEventListener('input',e=>mats.forEach(m=>m.opacity=+e.target.value));$('#reset').addEventListener('click',()=>setStage(current));$('#timeline').addEventListener('input',e=>setStage(order[Math.round(+e.target.value/100*(order.length-1))]));$('#play').addEventListener('click',()=>{const tl=gsap.timeline();order.forEach((s,i)=>tl.call(()=>setStage(s),[],i?1.35:0))});$('#pause').addEventListener('click',()=>gsap.globalTimeline.pause());
function resize(){const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}addEventListener('resize',resize);resize();setStage('overview');
(function loop(){requestAnimationFrame(loop);controls.update();marker.rotation.z+=.01;renderer.render(scene,camera)})();
